// <auto-generated />
using System;
using AtivosApi.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtivosApi.Migrations;

[DbContext(typeof(AtivoContext))]
partial class AtivoContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("AtivosApi.Models.Ativo", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("varchar(255)");

                b.Property<string>("AtivoNome")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<DateTime>("Data")
                    .HasColumnType("datetime(6)");

                b.Property<decimal>("Valor")
                    .HasColumnType("decimal(65,30)");

                b.Property<decimal>("VariacaoDiaAnterior")
                    .HasColumnType("decimal(65,30)");

                b.Property<decimal>("VariacaoPrimeiraData")
                    .HasColumnType("decimal(65,30)");

                b.HasKey("Id");

                b.ToTable("Ativos");
            });
#pragma warning restore 612, 618
    }
}
